### ISSUE TITLE
Resource representation is only available with these Content-Types:\napplication/json; charset=UTF-8

### ISSUE THREAD

**Issue by golisandeep3** [apache/incubator-openwhisk-package-kafka#177]
{
    "activationId": "fb53bf3368bc4f60bb6730d50fda3f9b",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "guest/messaging/kafkaFeed"
        }
    ],
    "duration": 50,
    "end": 1496449973679,
    "logs": [],
    "name": "kafkaFeed",
    "namespace": "guest",
    "publish": false,
    "response": {
        "result": {
            "error": {
                "code": 4715,
                "error": "Resource representation is only available with these Content-Types:\napplication/json; charset=UTF-8"
            }
        },
        "status": "application error",
        "success": false
    },
    "start": 1496449973629,
    "subject": "guest",
    "version": "0.0.2"
}
I see this error when i am trying to create a trigger 
wsk trigger create /guest/MyKafkaTrigger -f /guest/messaging/kafkaFeed -p brokers "[\"192.168.33.13:5000\"]" -p topic mytopic -p isJSONData false -p endpoint 192.168.33.13

**Comment by bjustin-ibm** [comment]
@golisandeep3 Just off the top of my head, it looks like may need to escape quotes around your broker `-p brokers "[\"192.168.33.13:5000\"]"`. Additionally, the brokers param also accepts a comma-separated list of brokers, which would free you from having to use JSON format on the command line.

Please let me know if this resolves your issue.
