### ISSUE TITLE
Make sendMessage action more stable

### ISSUE THREAD

**Issue by cbickel** [apache/incubator-openwhisk-package-kafka#182]
There could be the error, that it is not possible to establish a connection to Kafka.
As already discussed, we can add retries into the action, to avoid intermittend hickups.
It would be also great, if we could enhance the logging output of the action, to know instantly, at which point the action has thrown the error.
As third idea, it would be great (I don't know if it is possible) if we could log more information why it was not possible to connect to Kafka.

**Comment by bjustin-ibm** [comment]
Resolved by #202
