### ISSUE TITLE
Document How to Delete Trigger

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk-package-kafka#50]
The feed package_endpoint parameter must be specified when deleting a trigger. Otherwise, the consumer will not be removed from the service.

**Comment by bjustin-ibm** [comment]
It is expected that this parameter will have a bound value when the feed actions are deployed.  As such, I don't expect we'll want to document it in such a way that it seems like the user creating/deleting triggers should be concerned about it.

@jasonpet I think the Cloudant and Alarms feeds are the same. Do you have any thoughts on this?
