### ISSUE TITLE
Expose health information to trigger owner

### ISSUE THREAD

**Issue by bjustin-ibm** [apache/incubator-openwhisk-package-kafka#53]
In cases where the consumer can no longer continue (message hub instance removed, authentication changed, etc.) the last thing the consumer should do before shutting down is to post to the trigger URL. The body of this post should include useful information to inform the OW user that their trigger is being disabled and, if possible, provide a reason why.

**Comment by bjustin-ibm** [comment]
A very interesting alternative (proposed by @rabbah) is to instead have an action which allows users to get the status of their triggers. Users can run this action to see if their trigger is healthy and, if not, what might have happened to cause it to become unhealthy and/or removed.

**Comment by mimy2001** [comment]
Do you have this in a side branch anywhere? I'm having issues right now where the consumer keeps getting killed when I create the trigger and I don't know why that's happening.

**Comment by csantanapr** [comment]
This is now implemented with the new lifecycle `READ` on the feed action

**Comment by bjustin-ibm** [comment]
👍👍
