### ISSUE TITLE
Document how to Build and Deploy

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk-package-kafka#99]
The README must be updated to demonstrate to users how to build and deploy the service.

**Comment by mimy2001** [comment]
Has there been any documents or quick help provided to get this going with Openwhisk and CouchDB?
I don't have a Cloudant db, is it still possible to use this?

**Comment by bjustin-ibm** [comment]
@mimy2001 At the moment, CouchDB support is not tested, although some work has been done in #88 to make this possible. Cloudant is a superset of CouchDB, but I don't think we are using any of the Cloudant-specific features that are not in CouchDB. As such, I would think the work in #88 could be generalized to always use CouchDB - instead of switching between Cloudant/Couch based on a configuration flag as is proposed in #88 

The trouble is that #88 has probably rotted a bit due to its age. Perhaps you can revive it?

**Comment by mimy2001** [comment]
@bjustin-ibm Thanks for showing #88 to me, I'll give that a try in my environment and see if it works.  Any reason why #88 was not merged into the main branch even though there was work done on it?

**Comment by bjustin-ibm** [comment]
@mimy2001 I think the only reason it wasn't merged earlier was because it was a lower-priority item at the time, and we were scrambling to complete other features. Now that we have a user that has a use-case for it, the priority definitely goes up a few notches 😉 

If you get it working, please open a PR and we'll work on getting it merged.

**Comment by mimy2001** [comment]
So I got the image up and working but when I tried to create a trigger, I ran into issues:


if (params.lifecycleEvent === 'CREATE') {
            // makes a PUT request to create the trigger in the feed service provider
            var putTrigger = function(validatedParams) {
                var body = validatedParams;

                // params.endpoint may already include the protocol - if so,
                // strip it out
                var massagedAPIHost = params.endpoint.replace(/https?:\/\/(.*)/, "$1");
                body.triggerURL = 'https://' + process.env['__OW_API_KEY'] + "@" + massagedAPIHost + '/api/v1/namespaces/' + namespace + '/triggers/' + trigger;

                var options = {
                    method: 'PUT',
                    url: feedServiceURL,
                    body: JSON.stringify(body),
                    headers: {
                        'Content-Type': 'application/json',
                        'User-Agent': 'whisk'
                    }
                };

                return doRequest(options);
            };

When the following code executes to doRequest, I'm getting a failure:

error { Error: socket hang up
2017-04-10T19:59:34.690359375Z stdout: at createHangUpError (_http_client.js:254:15)
2017-04-10T19:59:34.690380981Z stdout: at Socket.socketOnEnd (_http_client.js:346:23)
2017-04-10T19:59:34.690388747Z stdout: at emitNone (events.js:91:20)
2017-04-10T19:59:34.690395579Z stdout: at Socket.emit (events.js:185:7)
2017-04-10T19:59:34.690402333Z stdout: at endReadableNT (_stream_readable.js:974:12)
2017-04-10T19:59:34.690409207Z stdout: at _combinedTickCallback (internal/process/next_tick.js:74:11)
2017-04-10T19:59:34.690416213Z stdout: at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }

I installed as : ./installKafka.sh `cat ~/openwhisk/ansible/files/auth.whisk.system` 172.17.0.1 172.17.0.1 9092 172.17.0.1

I have the ask action producing messages to kafka without problems. It's only the trigger that's not quite working now. Can you help me with this?

**Comment by bjustin-ibm** [comment]
Please post the output of `docker logs <kafka provider container>`

**Comment by mimy2001** [comment]
lzhao@sclg205:~/openwhisk-package-kafka$ docker logs ow_kafka
INFO:root:check_ssl is True <type 'bool'>
[2017-04-10 20:28:11,926] [INFO] [??] [kafkatriggers] check_ssl is True <type 'bool'>
INFO:root:enable_generic_kafka is True <type 'bool'>
[2017-04-10 20:28:11,927] [INFO] [??] [kafkatriggers] enable_generic_kafka is True <type 'bool'>
INFO:root:Starting DB migration
[2017-04-10 20:28:11,927] [INFO] [??] [kafkatriggers] Starting DB migration
INFO:root:design doc already exists
[2017-04-10 20:28:11,981] [INFO] [??] [kafkatriggers] design doc already exists
INFO:root:Database migration complete
[2017-04-10 20:28:11,982] [INFO] [??] [kafkatriggers] Database migration complete
INFO:root:Fetching all triggers from DB
[2017-04-10 20:28:11,983] [INFO] [??] [kafkatriggers] Fetching all triggers from DB
INFO:root:[Doctor] The Doctor is in!
[2017-04-10 20:28:11,992] [INFO] [??] [kafkatriggers] [Doctor] The Doctor is in!
INFO:root:Successfully retrieved 0 triggers
[2017-04-10 20:28:12,029] [INFO] [??] [kafkatriggers] Successfully retrieved 0 triggers

**Comment by mimy2001** [comment]
@bjustin-ibm 
so the kafka provider container, what port is it suppose to be running on? this would be the image I built from the Dockerfile right?

**Comment by mimy2001** [comment]
@bjustin-ibm I got it working

**Comment by bjustin-ibm** [comment]
@mimy2001 Ok, that looks pretty good. The most likely issue is that the port number/forwarding is wrong. By default, the provider service will listen on port 5000. You can change this by passing a `PORT` environment variable when starting the container but really... it's not that important to change since this is running inside the container. The most important part is that when you run the container, you expose whatever port the service is running on through the container.  For example:

`docker run -p 9092:5000 <image name>`

This command isn't complete. I omitted other key env variables that you seem to have already figured out 😉  However, this tells the container to pass requests from port 9092 outside the container into port 5000 inside the container. Whatever you decide to chose for your externally-visible port should be the port number passed into `installKafka.sh`. You can quickly check if the port forwarding is correct by hitting (in this example) `http://172.17.0.1:9092/health`

**Comment by bjustin-ibm** [comment]
@mimy2001 We have a public Slack team for all things OpenWhisk. It works a little better for this kind of back-and-forth conversation: http://slackindwo.mybluemix.net/

**Comment by mimy2001** [comment]
@bjustin-ibm ok thanks I've joined the slack channel.

**Comment by Sarah1024** [comment]
Hi there, is there any hint on how to get the service running? I am new to Openwhisk and I am trying to use this package to communicate with Kafka.

**Comment by bjustin-ibm** [comment]
@Sarah1024 Just to be clear, if you are using OpenWhisk on Bluemix, [this feed is already available to you](https://console.ng.bluemix.net/docs/openwhisk/openwhisk_messagehub.html#openwhisk_catalog_message_hub). However, if you are deploying your own OW, here is the very (very) short version of the build/deploy procedure for the Kafka feed provider:

Docker images are regularly published to [Docker Hub](https://hub.docker.com/r/openwhisk/kafkaprovider/tags/) with the latest stable tag currently being `1.0.18`. You can start the service by running: 
```
docker run -d -p 5000:5000 -e CLOUDANT_USER=<cloudant username> -e CLOUDANT_PASS=<cloudant password> openwhisk/kafkaProvider:1.0.18
``` 
Yes, this currently only works with Cloudant, but generic CouchDB support is likely coming. If you want to build your own docker image, you can certainly do that as well.

To install the actions, run: 
```
./installKafka.sh <AUTH> <EDGEHOST> <KAFKA_TRIGGER_HOST> <KAFKA_TRIGGER_PORT> <APIHOST>
``` 
Where `<AUTH>` is your OW API key for installing system-wide actions/packages, `<EDGEHOST>` and `<APIHOST>` are the IP:port of your OW controller, `<KAFKA_TRIGGER_HOST>` is the IP of the machine running the above container, and `<KAFKA_TRIGGER_PORT>` is 5000 (unless you customize it in the docker run command above. 

Or, if you are using Message Hub as your Kafka service, instead run `./installCatalog.sh` with the same exact arguments.

I hope this helps. Please let me know if you have any issues or, better, join us on Slack: http://slackindwo.mybluemix.net/

**Comment by Katiyman** [comment]
In the above intructions. I request one calrification from you @bjustin-ibm  that if my local openwhisk setup is using a ephermeral couchdb. cn i still install create one  coundant instance in bluemix and provide that cloudant details in docker run -d -p 5000:5000 -e CLOUDANT_USER=<cloudant username> -e CLOUDANT_PASS=<cloudant password> openwhisk/kafkaProvider:1.0.18

and it will run?

**Comment by bjustin-ibm** [comment]
@Katiyman I have not tested that scenario, but I can't think of any reason that wouldn't work. This is, however, a moot point now that CouchDB support has been merged into `master` via #160.

**Comment by Anuraag-Advani** [comment]
How would we deploy locally using CouchDB?

**Comment by bjustin-ibm** [comment]
@Anuraag-Advani I have written a development guide and added it to #187. Please review that pull request and let me know if you encounter any issues.

**Comment by Anuraag-Advani** [comment]
I am running openwhisk locally and do not have whisk.system/messaging installed, after running install.sh I get kafkaFeed in the guest namespace, so when I run  `wsk trigger create MyKafkaTrigger -f /whisk.system/messaging/kafkaFeed -p brokers "[\"mykafkahost:9092\", \"mykafkahost:9093\"]" -p topic mytopic -p isJSONData true`
It fails as it tries to find kafkaFeedWeb in the whisk.messaging namespace

**Comment by bjustin-ibm** [comment]
@Anuraag-Advani This is a problem that should be addressed by #181. Please verify that you have that change locally.

**Comment by Anuraag-Advani** [comment]
Yes I do

**Comment by bjustin-ibm** [comment]
Can you verify that you are using the `whisk.system` auth key as the first argument to `installKafka.sh`?

**Comment by bjustin-ibm** [comment]
Also, this conversation may go quicker if you join us on Slack: http://slackindwo.mybluemix.net/
😉

**Comment by Anuraag-Advani** [comment]
I think no, where is it located, I am using the the one in wskprops

**Comment by bjustin-ibm** [comment]
Ok, I think the `whisk.system` auth key is required. There are parts of this that assume the actions will be installed in the `whisk.system` namespace.
